packages:
  - packages/**

catalog:
  typescript: ^5.9.2
  unbuild: ^3.6.1
  vitest: ^3.2.4
  zod: ^4.1.5
  '@better-fetch/fetch': ^1.1.18
  better-call: ^1.0.15

catalogs:
  better-auth:
    '@better-auth/utils': ^0.2.6
    better-auth: ^1.3.8-beta.10
