packages:
  - dev/**
  - packages/**
  - apps/**

catalog:
  "@better-fetch/fetch": ^1.1.18
  better-call: 1.0.19
  better-sqlite3: ^12.4.6
  "@types/better-sqlite3": ^7.6.13
  typescript: ^5.9.3
  tsdown: ^0.16.6
  vitest: ^3.2.4
  zod: ^4.1.12

catalogs:
  better-auth:
    "@better-auth/utils": ^0.3.0
    better-auth: ^1.4.1

neverBuiltDependencies: []