packages:
  - dev/**
  - packages/**
  - apps/**

catalog:
  "@better-fetch/fetch": ^1.1.18
  better-call: ^1.0.15
  better-sqlite3: ^12.2.0
  "@types/better-sqlite3": ^7.6.13
  typescript: ^5.9.2
  unbuild: ^3.6.1
  vitest: ^3.2.4
  zod: ^4.1.5

catalogs:
  better-auth:
    "@better-auth/utils": ^0.2.6
    better-auth: ^1.3.8

onlyBuiltDependencies:
  - better-sqlite3
