name: Report an Issue
description: Report unexpected behavior or broken functionality.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        This template is used for reporting a issue with better-auth-extended.

        Feature requests should be opened in [here](https://github.com/jslno/better-auth-extended/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.yml&title=)

        Before opening a new issue, please do a [search](https://github.com/jslno/better-auth-extended/issues) of existing issues and :+1: upvote the existing issue instead.
  - type: textarea
    attributes:
      label: To Reproduce
      description: A step-by-step description of how to reproduce the issue, based on the linked reproduction. Screenshots can be provided in the issue body below. If using code blocks, make sure that [syntax highlighting is correct](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) and double check that the rendered preview is not broken.
      placeholder: |
        Ex:
        1. Create a backend
        2. Create a frontend and use client
        3. X will happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current vs Expected behavior
      description: |
        A clear and concise description of what the bug is (e.g., screenshots, logs, etc.), and what you expected to happen.

        **Skipping this/failure to provide complete information of the bug will result in the issue being closed.**
      placeholder: 'Following the steps from the previous section, I expected A to happen, but I observed B instead.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: System info
      description: Output of `npx envinfo --system --browsers`
      render: bash
      placeholder: System and browsers
    validations:
      required: true
  - type: dropdown
    id: packages
    attributes:
      label: What package(s) are affected?
      description: Select all that apply
      options:
        - app-invite
        - onboarding
        - test-utils
        - internal-utils
        - internal-env
      multiple: true
    validations:
      required: true
  - type: textarea
    attributes:
      label: What package versions are you using
      description: Please provide the current version of the packages that you are reporting the bug on
    validations:
      required: true
  - type: textarea
    attributes:
      label: Auth config (if applicable)
      description: If you haven't already shared a reproducible example or don't think it's unrelated, please include your auth config. Make sure to remove any sensitive information.
      render: typescript
      value: |
        import { betterAuth } from "better-auth";
        export const auth = betterAuth({
          emailAndPassword: {  
            enabled: true
          },
        });
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Any extra information that might help us investigate. For example, is it only reproducible online, or locally too? Is the issue only happening in a specific browser? etc.
      placeholder: |
        I tested my reproduction against the latest release.